export const TASKS_FETCH = 'ADMIN/WORK/PROJECTS/TASKS/FETCH';
export const TASKS_SET = 'ADMIN/WORK/PROJECTS/TASKS/SET';
export const TASKS_BUSY = 'ADMIN/WORK/PROJECTS/TASKS/BUSY';
export const TASKS_ERROR = 'ADMIN/WORK/PROJECTS/TASKS/ERROR';

export const TASKS_CREATE = 'ADMIN/WORK/PROJECTS/TASKS/CREATE';
export const TASKS_UPDATE = 'ADMIN/WORK/PROJECTS/TASKS/UPDATE';
export const TASKS_DELETE = 'ADMIN/WORK/PROJECTS/TASKS/DELETE';
