src/
  modules/
    auth/
      components/
      screens/
        LoginScreen.js
      store/
        actions.js
        reducers.js
        sagas.js
        selectors.js
    common/
      components/
        Header.js
        Sidebar.js
        BottomTabBar.js
      screens/
        ProfileScreen.js
        SettingsScreen.js
        MessagesScreen.js
        NotificationsScreen.js
    admin/
      dashboard/
        components/
        screens/
          AdminDashboardScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      leads/
        components/
        screens/
          AdminLeadsScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      clients/
        components/
        screens/
          AdminClientsScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      works/
        components/
        screens/
          AdminWorksScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      hrms/
        components/
        screens/
          AdminHRMScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      finance/
        components/
        screens/
          AdminFinanceScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
    employee/
      dashboard/
        components/
        screens/
          EmployeeDashboardScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      leads/
        components/
        screens/
          EmployeeLeadsScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      works/
        components/
        screens/
          EmployeeWorksScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
      hr/
        components/
        screens/
          EmployeeHRScreen.js
        store/
          actions.js
          reducers.js
          sagas.js
          selectors.js
  navigation/
    AppNavigator.js
    AuthNavigator.js
    AdminNavigator.js
    EmployeeNavigator.js
    TabNavigator.js
    DrawerNavigator.js
  store/
    rootReducer.js
    rootSaga.js
    configureStore.js
  services/
    api.js
    authService.js
    storageService.js
  utils/
    constants.js
    helpers.js
    validators.js
  components/
    ui/
      Button.js
      Input.js
      Card.js
      Modal.js
      Loader.js
  assets/
    images/
    icons/
    fonts/