export const NS = 'ADMIN/FINANCE/INVOICE';

export const LIST_REQUEST = `${NS}/LIST_REQUEST`;
export const LIST_SUCCESS = `${NS}/LIST_SUCCESS`;
export const LIST_FAILURE = `${NS}/LIST_FAILURE`;

export const SET_FILTERS = `${NS}/SET_FILTERS`;
export const SET_PAGE = `${NS}/SET_PAGE`;
export const SET_SIZE = `${NS}/SET_SIZE`;

export const GET_ONE_REQUEST = `${NS}/GET_ONE_REQUEST`;
export const GET_ONE_SUCCESS = `${NS}/GET_ONE_SUCCESS`;
export const GET_ONE_FAILURE = `${NS}/GET_ONE_FAILURE`;

export const CREATE_REQUEST = `${NS}/CREATE_REQUEST`;
export const CREATE_SUCCESS = `${NS}/CREATE_SUCCESS`;
export const CREATE_FAILURE = `${NS}/CREATE_FAILURE`;

export const UPDATE_REQUEST = `${NS}/UPDATE_REQUEST`;
export const UPDATE_SUCCESS = `${NS}/UPDATE_SUCCESS`;
export const UPDATE_FAILURE = `${NS}/UPDATE_FAILURE`;

export const UPLOAD_FILE_REQUEST = `${NS}/UPLOAD_FILE_REQUEST`;
export const UPLOAD_FILE_SUCCESS = `${NS}/UPLOAD_FILE_SUCCESS`;
export const UPLOAD_FILE_FAILURE = `${NS}/UPLOAD_FILE_FAILURE`;

export const DELETE_FILE_REQUEST = `${NS}/DELETE_FILE_REQUEST`;
export const DELETE_FILE_SUCCESS = `${NS}/DELETE_FILE_SUCCESS`;
export const DELETE_FILE_FAILURE = `${NS}/DELETE_FILE_FAILURE`;

export const REMINDER_REQUEST = `${NS}/REMINDER_REQUEST`;
export const REMINDER_SUCCESS = `${NS}/REMINDER_SUCCESS`;
export const REMINDER_FAILURE = `${NS}/REMINDER_FAILURE`;

export const MARK_PAID_REQUEST = `${NS}/MARK_PAID_REQUEST`;
export const MARK_PAID_SUCCESS = `${NS}/MARK_PAID_SUCCESS`;
export const MARK_PAID_FAILURE = `${NS}/MARK_PAID_FAILURE`;

export const ADD_RECEIPT_REQUEST = `${NS}/ADD_RECEIPT_REQUEST`;
export const ADD_RECEIPT_SUCCESS = `${NS}/ADD_RECEIPT_SUCCESS`;
export const ADD_RECEIPT_FAILURE = `${NS}/ADD_RECEIPT_FAILURE`;

export const LIST_RECEIPTS_REQUEST = `${NS}/LIST_RECEIPTS_REQUEST`;
export const LIST_RECEIPTS_SUCCESS = `${NS}/LIST_RECEIPTS_SUCCESS`;
export const LIST_RECEIPTS_FAILURE = `${NS}/LIST_RECEIPTS_FAILURE`;

export const ADD_PAYMENT_REQUEST = `${NS}/ADD_PAYMENT_REQUEST`;
export const ADD_PAYMENT_SUCCESS = `${NS}/ADD_PAYMENT_SUCCESS`;
export const ADD_PAYMENT_FAILURE = `${NS}/ADD_PAYMENT_FAILURE`;

export const LIST_PAYMENTS_REQUEST = `${NS}/LIST_PAYMENTS_REQUEST`;
export const LIST_PAYMENTS_SUCCESS = `${NS}/LIST_PAYMENTS_SUCCESS`;
export const LIST_PAYMENTS_FAILURE = `${NS}/LIST_PAYMENTS_FAILURE`;

export const DELETE_REQUEST = `${NS}/DELETE_REQUEST`;
export const DELETE_SUCCESS = `${NS}/DELETE_SUCCESS`;
export const DELETE_FAILURE = `${NS}/DELETE_FAILURE`;
