export const NS = 'admin/clients';
export const LIST_REQUEST = `${NS}/LIST_REQUEST`;
export const LIST_SUCCESS = `${NS}/LIST_SUCCESS`;
export const LIST_FAILURE = `${NS}/LIST_FAILURE`;

export const CREATE_REQUEST = `${NS}/CREATE_REQUEST`;
export const CREATE_SUCCESS = `${NS}/CREATE_SUCCESS`;
export const CREATE_FAILURE = `${NS}/CREATE_FAILURE`;

export const UPDATE_REQUEST = `${NS}/UPDATE_REQUEST`;
export const UPDATE_SUCCESS = `${NS}/UPDATE_SUCCESS`;
export const UPDATE_FAILURE = `${NS}/UPDATE_FAILURE`;

export const DELETE_REQUEST = `${NS}/DELETE_REQUEST`;
export const DELETE_SUCCESS = `${NS}/DELETE_SUCCESS`;
export const DELETE_FAILURE = `${NS}/DELETE_FAILURE`;

// keep existing constants above...
export const CATEGORY_LIST_REQUEST = `${NS}/CATEGORY_LIST_REQUEST`;
export const CATEGORY_LIST_SUCCESS = `${NS}/CATEGORY_LIST_SUCCESS`;
export const CATEGORY_LIST_FAILURE = `${NS}/CATEGORY_LIST_FAILURE`;

export const CATEGORY_CREATE_REQUEST = `${NS}/CATEGORY_CREATE_REQUEST`;
export const CATEGORY_CREATE_SUCCESS = `${NS}/CATEGORY_CREATE_SUCCESS`;
export const CATEGORY_CREATE_FAILURE = `${NS}/CATEGORY_CREATE_FAILURE`;

export const CATEGORY_DELETE_REQUEST = `${NS}/CATEGORY_DELETE_REQUEST`;
export const CATEGORY_DELETE_SUCCESS = `${NS}/CATEGORY_DELETE_SUCCESS`;
export const CATEGORY_DELETE_FAILURE = `${NS}/CATEGORY_DELETE_FAILURE`;

export const SUBCATEGORY_LIST_REQUEST = `${NS}/SUBCATEGORY_LIST_REQUEST`;
export const SUBCATEGORY_LIST_SUCCESS = `${NS}/SUBCATEGORY_LIST_SUCCESS`;
export const SUBCATEGORY_LIST_FAILURE = `${NS}/SUBCATEGORY_LIST_FAILURE`;

export const SUBCATEGORY_CREATE_REQUEST = `${NS}/SUBCATEGORY_CREATE_REQUEST`;
export const SUBCATEGORY_CREATE_SUCCESS = `${NS}/SUBCATEGORY_CREATE_SUCCESS`;
export const SUBCATEGORY_CREATE_FAILURE = `${NS}/SUBCATEGORY_CREATE_FAILURE`;

export const SUBCATEGORY_DELETE_REQUEST = `${NS}/SUBCATEGORY_DELETE_REQUEST`;
export const SUBCATEGORY_DELETE_SUCCESS = `${NS}/SUBCATEGORY_DELETE_SUCCESS`;
export const SUBCATEGORY_DELETE_FAILURE = `${NS}/SUBCATEGORY_DELETE_FAILURE`;
