// Profile
export const ADMIN_PROFILE_UPDATE_REQUEST = 'ADMIN_PROFILE_UPDATE_REQUEST';
export const ADMIN_PROFILE_UPDATE_SUCCESS = 'ADMIN_PROFILE_UPDATE_SUCCESS';
export const ADMIN_PROFILE_UPDATE_FAILURE = 'ADMIN_PROFILE_UPDATE_FAILURE';

// Company
export const ADMIN_COMPANY_FETCH_REQUEST = 'ADMIN_COMPANY_FETCH_REQUEST';
export const ADMIN_COMPANY_FETCH_SUCCESS = 'ADMIN_COMPANY_FETCH_SUCCESS';
export const ADMIN_COMPANY_FETCH_FAILURE = 'ADMIN_COMPANY_FETCH_FAILURE';

export const ADMIN_COMPANY_SAVE_REQUEST = 'ADMIN_COMPANY_SAVE_REQUEST';
export const ADMIN_COMPANY_SAVE_SUCCESS = 'ADMIN_COMPANY_SAVE_SUCCESS';
export const ADMIN_COMPANY_SAVE_FAILURE = 'ADMIN_COMPANY_SAVE_FAILURE';
