export const FETCH_PROJECT_ACTIVITY_REQUEST =
  'employee/projects/FETCH_PROJECT_ACTIVITY_REQUEST';
export const FETCH_PROJECT_ACTIVITY_SUCCESS =
  'employee/projects/FETCH_PROJECT_ACTIVITY_SUCCESS';
export const FETCH_PROJECT_ACTIVITY_FAILURE =
  'employee/projects/FETCH_PROJECT_ACTIVITY_FAILURE';
