export const EMP_PROJ_FETCH_REQUEST = 'EMP_PROJ_FETCH_REQUEST';
export const EMP_PROJ_FETCH_SUCCESS = 'EMP_PROJ_FETCH_SUCCESS';
export const EMP_PROJ_FETCH_FAILURE = 'EMP_PROJ_FETCH_FAILURE';

export const EMP_PROJ_OPEN_MODAL = 'EMP_PROJ_OPEN_MODAL';
export const EMP_PROJ_CLOSE_MODAL = 'EMP_PROJ_CLOSE_MODAL';

export const EMP_PROJ_CREATE_REQUEST = 'EMP_PROJ_CREATE_REQUEST';
export const EMP_PROJ_CREATE_SUCCESS = 'EMP_PROJ_CREATE_SUCCESS';
export const EMP_PROJ_CREATE_FAILURE = 'EMP_PROJ_CREATE_FAILURE';

export const EMP_PROJ_UPDATE_REQUEST = 'EMP_PROJ_UPDATE_REQUEST';
export const EMP_PROJ_UPDATE_SUCCESS = 'EMP_PROJ_UPDATE_SUCCESS';
export const EMP_PROJ_UPDATE_FAILURE = 'EMP_PROJ_UPDATE_FAILURE';

export const EMP_PROJ_DELETE_REQUEST = 'EMP_PROJ_DELETE_REQUEST';
export const EMP_PROJ_DELETE_SUCCESS = 'EMP_PROJ_DELETE_SUCCESS';
export const EMP_PROJ_DELETE_FAILURE = 'EMP_PROJ_DELETE_FAILURE';

export const EMP_PROJ_STATUS_REQUEST = 'EMP_PROJ_STATUS_REQUEST';
export const EMP_PROJ_STATUS_SUCCESS = 'EMP_PROJ_STATUS_SUCCESS';
export const EMP_PROJ_STATUS_FAILURE = 'EMP_PROJ_STATUS_FAILURE';
