export const FETCH_HOLIDAYS_REQUEST = 'ADMIN/HOLIDAYS/FETCH_REQUEST';
export const FETCH_HOLIDAYS_SUCCESS = 'ADMIN/HOLIDAYS/FETCH_SUCCESS';
export const FETCH_HOLIDAYS_FAILURE = 'ADMIN/HOLIDAYS/FETCH_FAILURE';

export const CREATE_HOLIDAYS_REQUEST = 'ADMIN/HOLIDAYS/CREATE_REQUEST';
export const CREATE_HOLIDAYS_SUCCESS = 'ADMIN/HOLIDAYS/CREATE_SUCCESS';
export const CREATE_HOLIDAYS_FAILURE = 'ADMIN/HOLIDAYS/CREATE_FAILURE';

export const OPEN_HOLIDAY_MODAL = 'ADMIN/HOLIDAYS/OPEN_MODAL';
export const CLOSE_HOLIDAY_MODAL = 'ADMIN/HOLIDAYS/CLOSE_MODAL';

export const SET_HOLIDAY_FILTERS = 'ADMIN/HOLIDAYS/SET_FILTERS';
export const SET_HOLIDAY_MODE = 'ADMIN/HOLIDAYS/SET_MODE'; // 'list' | 'calendar'
