export const FETCH_HOLIDAYS_REQUEST = 'ADMIN/HOLIDAYS/FETCH_REQUEST';
export const FETCH_HOLIDAYS_SUCCESS = 'ADMIN/HOLIDAYS/FETCH_SUCCESS';
export const FETCH_HOLIDAYS_FAILURE = 'ADMIN/HOLIDAYS/FETCH_FAILURE';

export const CREATE_HOLIDAYS_REQUEST = 'ADMIN/HOLIDAYS/CREATE_REQUEST';
export const CREATE_HOLIDAYS_SUCCESS = 'ADMIN/HOLIDAYS/CREATE_SUCCESS';
export const CREATE_HOLIDAYS_FAILURE = 'ADMIN/HOLIDAYS/CREATE_FAILURE';

export const OPEN_HOLIDAY_MODAL = 'ADMIN/HOLIDAYS/OPEN_MODAL';
export const CLOSE_HOLIDAY_MODAL = 'ADMIN/HOLIDAYS/CLOSE_MODAL';

export const SET_HOLIDAY_FILTERS = 'ADMIN/HOLIDAYS/SET_FILTERS';
export const SET_HOLIDAY_MODE = 'ADMIN/HOLIDAYS/SET_MODE'; // 'list' | 'calendar'

export const OPEN_HOLIDAY_EDIT_MODAL = 'ADMIN/HOLIDAYS/OPEN_EDIT_MODAL';
export const UPDATE_HOLIDAY_REQUEST = 'ADMIN/HOLIDAYS/UPDATE_REQUEST';
export const UPDATE_HOLIDAY_SUCCESS = 'ADMIN/HOLIDAYS/UPDATE_SUCCESS';
export const UPDATE_HOLIDAY_FAILURE = 'ADMIN/HOLIDAYS/UPDATE_FAILURE';

export const DELETE_HOLIDAY_REQUEST = 'ADMIN/HOLIDAYS/DELETE_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'ADMIN/HOLIDAYS/DELETE_SUCCESS';
export const DELETE_HOLIDAY_FAILURE = 'ADMIN/HOLIDAYS/DELETE_FAILURE';
