export const PREFIX = 'admin/clientsViewDocuments';

export const LIST_BY_CLIENT_REQUEST = `${PREFIX}/LIST_BY_CLIENT_REQUEST`;
export const LIST_BY_CLIENT_SUCCESS = `${PREFIX}/LIST_BY_CLIENT_SUCCESS`;
export const LIST_BY_CLIENT_FAILURE = `${PREFIX}/LIST_BY_CLIENT_FAILURE`;

export const UPLOAD_REQUEST = `${PREFIX}/UPLOAD_REQUEST`;
export const UPLOAD_SUCCESS = `${PREFIX}/UPLOAD_SUCCESS`;
export const UPLOAD_FAILURE = `${PREFIX}/UPLOAD_FAILURE`;

export const DELETE_REQUEST = `${PREFIX}/DELETE_REQUEST`;
export const DELETE_SUCCESS = `${PREFIX}/DELETE_SUCCESS`;
export const DELETE_FAILURE = `${PREFIX}/DELETE_FAILURE`;
