export const MODULE = 'admin/deals';

// list / get
export const FETCH_LIST_REQUEST = `${MODULE}/FETCH_LIST_REQUEST`;
export const FETCH_LIST_SUCCESS = `${MODULE}/FETCH_LIST_SUCCESS`;
export const FETCH_LIST_FAILURE = `${MODULE}/FETCH_LIST_FAILURE`;

export const FETCH_ONE_REQUEST = `${MODULE}/FETCH_ONE_REQUEST`;
export const FETCH_ONE_SUCCESS = `${MODULE}/FETCH_ONE_SUCCESS`;
export const FETCH_ONE_FAILURE = `${MODULE}/FETCH_ONE_FAILURE`;

// create / update / delete
export const CREATE_REQUEST = `${MODULE}/CREATE_REQUEST`;
export const CREATE_SUCCESS = `${MODULE}/CREATE_SUCCESS`;
export const CREATE_FAILURE = `${MODULE}/CREATE_FAILURE`;

export const UPDATE_REQUEST = `${MODULE}/UPDATE_REQUEST`;
export const UPDATE_SUCCESS = `${MODULE}/UPDATE_SUCCESS`;
export const UPDATE_FAILURE = `${MODULE}/UPDATE_FAILURE`;

export const DELETE_REQUEST = `${MODULE}/DELETE_REQUEST`;
export const DELETE_SUCCESS = `${MODULE}/DELETE_SUCCESS`;
export const DELETE_FAILURE = `${MODULE}/DELETE_FAILURE`;

// followups
export const FOLLOWUP_CREATE_REQUEST = `${MODULE}/FOLLOWUP_CREATE_REQUEST`;
export const FOLLOWUP_CREATE_SUCCESS = `${MODULE}/FOLLOWUP_CREATE_SUCCESS`;
export const FOLLOWUP_CREATE_FAILURE = `${MODULE}/FOLLOWUP_CREATE_FAILURE`;

// ui helpers
export const SET_BUSY = `${MODULE}/SET_BUSY`;
export const SET_PARAMS = `${MODULE}/SET_PARAMS`;
export const SET_FORM_OPEN = `${MODULE}/SET_FORM_OPEN`;
export const SET_EDITING = `${MODULE}/SET_EDITING`;
export const SET_FOLLOWUP_OPEN = `${MODULE}/SET_FOLLOWUP_OPEN`;
